spring:
  security:
    user:
      name: user
      password: password
  datasource:
    platform: h2
    url: jdbc:h2:mem:RecLoc;DB_CLOSE_DELAY=-1
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        cache.use_query_cache: false
        show_sql: true
server:
  port: 9095
